CREATE TABLE Users (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	username TEXT UNIQUE NOT NULL,
	email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	profilePicture TEXT
);

CREATE TABLE Sessions (
	id TEXT PRIMARY KEY,
	userId INTEGER NOT NULL,
	data TEXT,
	createdAt TIMESTAMP NOT NULL,
	expiresAt TIMESTAMP NOT NULL,
	FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE Urls (
  id SERIAL PRIMARY KEY, 
	shortUrl TEXT NOT NULL, 
	originalUrl TEXT NOT NULL, 
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	expiresAt TIMESTAMP, 
	clicks INTEGER DEFAULT 0, 
	userId INTEGER, 
	isActive BOOLEAN DEFAULT TRUE
);